"""empty message

Revision ID: 0ed646f70150
Revises: e960f2e80319
Create Date: 2016-08-29 11:02:56.635029

"""

# revision identifiers, used by Alembic.
revision = '0ed646f70150'
down_revision = 'e960f2e80319'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('degrees', sa.String(length=255), nullable=True),
    sa.Column('other_degrees', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('work_phone', sa.String(length=255), nullable=True),
    sa.Column('fax', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('alternate_email', sa.String(length=255), nullable=True),
    sa.Column('work_environment', sa.String(length=255), nullable=True),
    sa.Column('health_research_topic', sa.String(length=255), nullable=True),
    sa.Column('health_research_method', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration')
    ### end Alembic commands ###
