"""empty message

Revision ID: 13a436001f5e
Revises: fc241365605b
Create Date: 2016-09-06 16:19:15.649523

"""

# revision identifiers, used by Alembic.
revision = '13a436001f5e'
down_revision = 'fc241365605b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('dl_av', sa.Float(), nullable=True))
    op.add_column('exam', sa.Column('hx_av', sa.Float(), nullable=True))
    op.add_column('exam', sa.Column('ls_av', sa.Float(), nullable=True))
    op.add_column('exam', sa.Column('sw_av', sa.Float(), nullable=True))
    op.add_column('exam', sa.Column('sx_av', sa.Float(), nullable=True))
    op.add_column('exam', sa.Column('wl_av', sa.Float(), nullable=True))
    op.add_column('exam', sa.Column('yw_av', sa.Float(), nullable=True))
    op.add_column('exam', sa.Column('yy_av', sa.Float(), nullable=True))
    op.add_column('exam', sa.Column('zz_av', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'zz_av')
    op.drop_column('exam', 'yy_av')
    op.drop_column('exam', 'yw_av')
    op.drop_column('exam', 'wl_av')
    op.drop_column('exam', 'sx_av')
    op.drop_column('exam', 'sw_av')
    op.drop_column('exam', 'ls_av')
    op.drop_column('exam', 'hx_av')
    op.drop_column('exam', 'dl_av')
    ### end Alembic commands ###
