"""empty message

Revision ID: 1427559edc75
Revises: 13a436001f5e
Create Date: 2016-10-12 15:36:03.654831

"""

# revision identifiers, used by Alembic.
revision = '1427559edc75'
down_revision = '13a436001f5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('sx_stand', sa.Float(), nullable=True))
    op.add_column('score', sa.Column('yw_stand', sa.Float(), nullable=True))
    op.add_column('score', sa.Column('yy_stand', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'yy_stand')
    op.drop_column('score', 'yw_stand')
    op.drop_column('score', 'sx_stand')
    ### end Alembic commands ###
