"""empty message

Revision ID: 265b22e99801
Revises: None
Create Date: 2016-11-09 15:47:29.257347

"""

# revision identifiers, used by Alembic.
revision = '265b22e99801'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('yw_av', sa.Float(), nullable=True),
    sa.Column('sx_av', sa.Float(), nullable=True),
    sa.Column('yy_av', sa.Float(), nullable=True),
    sa.Column('wl_hg_av', sa.Float(), nullable=True),
    sa.Column('hx_hg_av', sa.Float(), nullable=True),
    sa.Column('wl_dj_av', sa.Float(), nullable=True),
    sa.Column('hx_dj_av', sa.Float(), nullable=True),
    sa.Column('sw_av', sa.Float(), nullable=True),
    sa.Column('ls_av', sa.Float(), nullable=True),
    sa.Column('zz_av', sa.Float(), nullable=True),
    sa.Column('dl_av', sa.Float(), nullable=True),
    sa.Column('yw_stand_av', sa.Float(), nullable=True),
    sa.Column('sx_stand_av', sa.Float(), nullable=True),
    sa.Column('yy_stand_av', sa.Float(), nullable=True),
    sa.Column('wl_stand_av', sa.Float(), nullable=True),
    sa.Column('hx_stand_av', sa.Float(), nullable=True),
    sa.Column('sw_stand_av', sa.Float(), nullable=True),
    sa.Column('ls_stand_av', sa.Float(), nullable=True),
    sa.Column('zz_stand_av', sa.Float(), nullable=True),
    sa.Column('dl_stand_av', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('open_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=15), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_ip', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yw', sa.Float(), nullable=True),
    sa.Column('yw_stand', sa.Float(), nullable=True),
    sa.Column('sx', sa.Float(), nullable=True),
    sa.Column('sx_stand', sa.Float(), nullable=True),
    sa.Column('yy', sa.Float(), nullable=True),
    sa.Column('yy_stand', sa.Float(), nullable=True),
    sa.Column('wl_hg', sa.Float(), nullable=True),
    sa.Column('wl_dj', sa.Float(), nullable=True),
    sa.Column('wl_stand', sa.Float(), nullable=True),
    sa.Column('hx_hg', sa.Float(), nullable=True),
    sa.Column('hx_dj', sa.Float(), nullable=True),
    sa.Column('hx_stand', sa.Float(), nullable=True),
    sa.Column('sw', sa.Float(), nullable=True),
    sa.Column('sw_stand', sa.Float(), nullable=True),
    sa.Column('dl', sa.Float(), nullable=True),
    sa.Column('dl_stand', sa.Float(), nullable=True),
    sa.Column('ls', sa.Float(), nullable=True),
    sa.Column('ls_stand', sa.Float(), nullable=True),
    sa.Column('zz', sa.Float(), nullable=True),
    sa.Column('zz_stand', sa.Float(), nullable=True),
    sa.Column('sum_3', sa.Float(), nullable=True),
    sa.Column('class_rank_3', sa.Integer(), nullable=True),
    sa.Column('grade_rank_3', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('student')
    op.drop_table('roles')
    op.drop_table('exam')
    ### end Alembic commands ###
