"""empty message

Revision ID: 398e90ae5771
Revises: 77cbfef551e8
Create Date: 2016-09-08 16:33:50.072645

"""

# revision identifiers, used by Alembic.
revision = '398e90ae5771'
down_revision = '77cbfef551e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pip_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['photo'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['photo'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio', sa.Integer(), nullable=True),
    sa.Column('photo', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audio'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['photo'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pip_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('access_code', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.Integer(), nullable=True),
    sa.Column('video', sa.Integer(), nullable=True),
    sa.Column('podcast', sa.Integer(), nullable=True),
    sa.Column('cv', sa.Integer(), nullable=True),
    sa.Column('news', sa.Integer(), nullable=True),
    sa.Column('portfolio', sa.Integer(), nullable=True),
    sa.Column('pip_block', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cv'], ['cv.id'], ),
    sa.ForeignKeyConstraint(['news'], ['news.id'], ),
    sa.ForeignKeyConstraint(['photo'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['pip_block'], ['pip_block.id'], ),
    sa.ForeignKeyConstraint(['podcast'], ['podcast.id'], ),
    sa.ForeignKeyConstraint(['portfolio'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['video'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pip_user_email'), 'pip_user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pip_user_email'), table_name='pip_user')
    op.drop_table('pip_user')
    op.drop_table('podcast')
    op.drop_table('news')
    op.drop_table('cv')
    op.drop_table('resource')
    op.drop_table('portfolio')
    op.drop_table('pip_block')
    ### end Alembic commands ###
