"""empty message

Revision ID: 3fe25f498704
Revises: 27f5ad9226cc
Create Date: 2016-10-18 17:10:29.843382

"""

# revision identifiers, used by Alembic.
revision = '3fe25f498704'
down_revision = '27f5ad9226cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('content', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'content')
    ### end Alembic commands ###
